apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: APPSODY_PROJECT_NAME
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: APPSODY_DOCKER_IMAGE 
  stack: APPSODY_STACK
  serviceAccountName: serviceaccount
  createKnativeService: failureThreshold
  pullPolicy: Always
  #pullSecret: secret name to access private project on git  
  replicas: 1
  service:
    type: ClusterIP
    port: APPSODY_PORT
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/actuator/prometheus'
  monitoring:
    labels:
      k8s-app: APPSODY_PROJECT_NAME
    endpoints:
    - path: '/actuator/prometheus'
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/health
      port: APPSODY_PORT
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: APPSODY_PORT
    initialDelaySeconds: 5
    periodSeconds: 2
  expose: true
  env:
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        key: JWT_SECRET
        name: jwt-secret
  - name: AUTH_API_URI
    value: "http://login.apps.msg.darumtech.net"  
  resourceConstraints:
    limits:
      memory: 512Mi
      cpu: 2
    requests:
      cpu: 0.5
  autoscaling:
    targetCPUUtilizationPercentage: 50
    minReplicas: 1
    maxReplicas: 4
  storage:
    mountPath: "/logs"
    size: 1Gi